export { default as Home } from './Home/Home'
export { default as Friends } from './Friends'
export { default as Groups } from './Groups/Groups'
export { default as Group } from './Groups/Group'
export { default as Collections } from './Collections/Collections'
export { default as Collection } from './Collections/Collection'
export { default as Notifications } from './Notifications/Notifications'
export { default as Create } from './Create/Create'
export { default as Profile } from './Profile/Profile'
export { default as UserProfile } from './Profile copy/Profile'
export { default as More } from './More/More'
export { default as Codes } from './Codes'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'