// export const baseURL = 'https://codegem.glitch.me'
// export const baseURL = "https://codegem-orange.glitch.me";
// export const baseURL = 'https://codegem-server.vercel.app'
export const adminEmail = 'naumanch969@gmail.com'
export const SOCKET_URL = 'http://localhost:8900'

export const getEnvironment = (): 'production' | 'development' => { return 'production' };


export const baseURL = getEnvironment() == 'development' ? "http://localhost:5000" : 'https://codegem-server.vercel.app';

export const programmingLanguages = [
    "HTML",
    "CSS",
    "JavaScript",
    "Java",
    "Python",
    "R",
    "C",
    "C++",
    "C#",
    "PHP",
    "TypeScript",
    "Swift",
    "Kotlin",
    "Ruby",
    "Go",
    "SQL",
    "Perl",
    "Scala",
    "Rust",
    "Objective-C",
    "Shell",
    "Lua",
    "Assembly",
    "Dart",
    "MATLAB",
    "Groovy",
    "Visual Basic",
    "Delphi",
    "Haskell",
    "Julia",
    "PowerShell",
    "Clojure",
    "Elixir",
    "F#",
    "Scheme",
    "Fortran",
    "COBOL",
    "Ada",
    "Lisp",
    "Prolog",
    "Smalltalk",
    "Racket",
    "Erlang",
    "Verilog",
    "VHDL",
    "Scratch",
    "Bash",
    "Tcl",
    "Forth",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express",
    "Django",
    "Flask",
    "Spring",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "Gatsby",
    "Next.js",
    "Nuxt.js",
    "Ember.js",
    "Svelte",
    "Meteor",
    "Backbone.js",
    "Bootstrap",
    "jQuery",
    "Apache Struts",
    "CakePHP",
    "Ionic",
    "Cordova",
    "Titanium",
    "Dart Flutter",
    "Celery",
    "LangChain",
    "FastAPI",
    "GraphQL",
    "Apollo",
    "RxJava",
    "RxJS",
    "Mockito",
    "JUnit",
    "JUnit 5",
    "JUnit 4",
    "TestNG",
    "Cucumber",
    "Selenium",
    "JUnit",
    "Jasmine",
    "Karma",
    "Protractor"
];

