
export enum SettingParentField {
    account = 'account',
    privacy = 'privacy',
    notification = 'notification',
    themeAndDisplay = 'themeAndDisplay',
    connectedAccounts = 'connectedAccounts',
    accessibility = 'accessibility',
}
export enum SettingSubField {
    username = 'username',
    fullName = 'fullName',
    email = 'email',
    location = 'location',
    bio = 'bio',
    profileVisibility = 'profileVisibility',
    whoCanSendFriendRequests = 'whoCanSendFriendRequests',
    whoCanSeeMyFriendsList = 'whoCanSeeMyFriendsList',
    whoCanSeeMyPosts = 'whoCanSeeMyPosts',
    whoCanTagMeInPosts = 'whoCanTagMeInPosts',
    blockUsers = 'blockUsers',
    emailNotifications = 'emailNotifications',
    pushNotifications = 'pushNotifications',
    manageNotificationPreferences = 'manageNotificationPreferences',
    mode = 'mode',
    adjustFontSize = 'adjustFontSize',
    facebook = 'facebook',
    twitter = 'twitter',
    github = 'github',
    enableAccessibilityFeatures = 'enableAccessibilityFeatures',
}